org: andreacoa
service: api-songs

provider:
  name: aws
  runtime: nodejs20.x
  # Default memory size for functions (default: 256MB)
  memorySize: 512
  timeout: 30
  iam:
    role: arn:aws:iam::123412341234:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_songs # modificar

functions:
get_all_songs:
  handler: lambda_get_all.handler
  events:
    - http:
        path: /songs/
        method: get
        cors: true
        integration: lambda
  get_song_by_genre:
    handler: lambda_getByGenre.handler
    events:
      - http:
          path: /songs/genre
          method: post
          cors: true
          integration: lambda
  get_song_by_artist_email:
    handler: lambda_getByArtistEmail.handler
    events:
      - http:
          path: /songs/artist
          method: post
          cors: true
          integration: lambda
  get_song_by_id:
    handler: lambda_getById.handler
    envents:
      - http:
          path: /songs/id
          method: post
          cors: true
          integration: lambda
  post_song:
    handler: lambda_post_song.handler
    events:
      - http:
          path: /songs/create
          method: post
          cors: true
          integration: lambda
    package:
      include:
        - node_modules/uuid/**
      exclude:
        - node_modules/**
        - '!node_modules/uuid/**'
# completar

resources:
  Resources:
    TablaSongs:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: artista_email
            AttributeType: S
          - AttributeName: genre#release-date
            AttributeType: S
          - AttributeName: song_uuid
            AttributeType: S
        KeySchema:
          - AttributeName: artista_email
            KeyType: HASH
          - AttributeName: genre#release-date
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: song_uuid-index
            KeySchema:
              - AttributeName: song_uuid
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
